name: Generate Markdown TOC

on:
  push:
    branches: 
      - '**'

jobs:
  generate-toc:
    name: Generate Table of Contents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate TOC for Markdown files
        uses: technote-space/markdown-toc@v3
        with:
          file_glob: 'docs/**/*.md'

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Generate/update Table of Contents in Markdown files" || echo "No changes to commit"
          git push
